### PR TITLE
Update plugin.js

### PR DESCRIPTION
**Pull request by SteveTheTechie**
Rather than sending JSON data to the server, I changed this to mimic what jQuery does (without needing jQuery). In other words, it now sends the post as multi-part form data with UTF-8 character set, just like jQuery does by default.  It also handles proper encoding of html containing special characters.  I have fully tested this to verify a jQuery like POST.

Most people will not want to have to deal with JSON data in a POST.

If you want to keep the JSON POST option, then I would suggest giving people an option to specify what in form they want the data send to the server.

Sorry for all the updates.  It is just that I am actually currently updating a web application to use this.

### CODE REVIEW

**Comment by tyleryasaka** [comment]
No, I think it's great that you're using it in a real-world application. I created the plugin for a little pet project of mine a year or 2 back when I was first getting into web development as a learning project. It worked for my purposes, but your changes make it something a lot more people will be able to use.

**Comment by tyleryasaka** [comment]
And my bad on missing your earlier commits. I realized later that merged pull requests are automatically closed. When the requests didn't close I thought it was strange and just manually closed them, not realizing you'd made new commits.

**Comment by tyleryasaka** [comment]
And I think I'll go ahead and allow the option of sending data as JSON like you said. But I'll leave multipart/form-data as the default.

**Comment by SteveTheTechie** [comment]
Might be helpful to also have a text file showing various use cases of how the callbacks can be used.  Maybe a callbacks.md file or similar.  Could contain sample code excerpts for using a spinner, undoing changes w/ onCancel, etc.

**Comment by SteveTheTechie** [comment]
BTW, have you tested sending data as JSON to verify it works?  I switched to multipart-form when it occurred to me that's what I needed to do to make it mimic jQuery (which is what I wanted).  As a result, I never made any effort to make the JSON approach work.

**Comment by tyleryasaka** [comment]
Yeah I like that idea. Since you're working on a real app with the plugin, would you want to put that together based on what you've done with it? I can also do it sometime, I'm just busy right now.

And yes I have been doing several tests on my code before each commit. On the last one I did it with and without JSON.

**Pull request merged**
