### PR TITLE
Update plugin.js

### PR DESCRIPTION
**Pull request by SteveTheTechie**
Since some of my prior commits were ignored without any comments or feedback, I am adding another pull request.
1. Don't use extra addData() function... superfluous and adds an extra function call where one is not needed.
2.  Allow showing spinner on save via onSave call back.
3.  Allow adding additional data to save via postData config parameter.
4. Send editor references to call backs to allow manipulating editor instances from call backs.
5. Ditch using jQuery... Not required and does not really add any benefit.

### CODE REVIEW

**Comment by tyleryasaka** [comment]
I'm not sure what commits you're referring to that were ignored. I pulled in all of your changes.

**Comment by SteveTheTechie** [comment]
No some were not pulled in...  Maybe you merged the wrong commit?

**Comment by tyleryasaka** [comment]
I merged the 2 pull requests that you made this morning, then had to go to work/school before I could test the changes and push them. Maybe you made the commits after I merged this morning.

**Comment by SteveTheTechie** [comment]
It is possible.   In any case, I just found that I goofed on this pull request, so I am going to do another commit to fix.

**Comment by tyleryasaka** [comment]
Gotcha.

**Comment by SteveTheTechie** [comment]
Ok, this last commit should be ok.  However, I am at my day job and cannot test right now, so feel free to test.

**Comment by tyleryasaka** [comment]
Will do.

**Comment by SteveTheTechie** [comment]
Some things that should be possible now, even with multiple inline editor instances on a web page:
1. Specify and save arbitrary data to the server along with the save.
2. Start a spinner via the onSave call back and remove it in either the onSuccess or onFailure callbacks.
3. Manipulate the editor instances from the call backs using the editor parameter passed to them.
4. Along with #3 above, undo changes w/ inlinesave onCancel call back, if original editor state saved prior to edits.  (No reload needed then.)

**Comment by tyleryasaka** [comment]
Thanks. I'll add something like that to the readme.

**Comment by SteveTheTechie** [comment]
Also, one thing I am doing in my onSuccess callback is the following:

editor.showNotification( 'Your content has been successfully saved.', 'success' );

This displays a very nice green notification pop-up using the new editor notification functionality.
This is a specific example of how I use the editor parameter.

**Comment by tyleryasaka** [comment]
Nice. I'm including that too.

**Comment by tyleryasaka** [comment]
All changes live.

**Pull request merged**
